### PR TITLE
Add all the rest targets support for sbt-haxe

### PR DESCRIPTION
**Pull request by zhanglongyang**
This is part of the implementation for #56 

Targets:
- php
- python
- c++
- neko
- flash
- action script 3

and https://github.com/new-cbs/sbt-haxe-sample is a project to verify it with samples

### CODE REVIEW

**Comment by Atry** [comment]
I wonder if we could disable all plugins except the Java target by default, since Sbt is a JVM-favored build tool.

We could simply remove this line in each of these plugins.
```
override final def trigger = allRequirements
```

**Comment by Atry** [comment]
We could bump `sbt-haxe` version to 1.4.0 as the behavior changes.

**Comment by zhanglongyang** [comment]
@Atry sounds very reasonable to me. :+1:

**Comment by zhanglongyang** [comment]
also there're still 2 targets left (as3 & flash), I'll add them today.

**Comment by zhanglongyang** [comment]
@Atry all done

**Comment by chank** [comment]
:+1:

**Pull request merged**
